### ISSUE TITLE
ld.so.preload location

### ISSUE THREAD

**Issue by imreiko** [mempodippy/vlany#1]
Great job... I just have one feature request, and I'm not sure if you'll like it.
In newer versions of Umbreon, we modify ld.so itself to change the location of ld.so.preload, and then hide this modification.
You may wanna do the same.

Seriously though, GREAT JOB ON THIS. I'm too busy with real life to really work on cool stuff like this anymore.

**Comment by mempodippy** [comment]
Once I correct any current bugs, I'll consider more additions.
