### ISSUE TITLE
Vlany installation fails when installing under /run or /sys

### ISSUE THREAD

**Issue by corefx** [mempodippy/vlany#10]
Hi,
/run is mounted as tmpfs (not persistent) and /sys is not writable. Tested on Debian 8 and Ubuntu 16.04.

**Comment by mempodippy** [comment]
I assume you mean for when patching the dynamic linker and using the new file. I've removed /run and /sys from the directory listing in patch_ld.py. Should be fixed. As for the installation directory of the shared libraries and whatnot; just don't edit the installation directory to install in /run or /sys.
