### ISSUE TITLE
Configuration Failed . Exitting 

### ISSUE THREAD

**Issue by directoryx** [mempodippy/vlany#15]
I was install vlany in Ubuntu 16.04 VMWare but always shown a error 
"Configuration Failed . Exitting "
when i use cli mode 
Error was shown like this :
Traceback (most recent call last):
  File "config.py", line 491, in <module>
    main()
  File "config.py", line 481, in main
    const_h_setup()
  File "config.py", line 207, in const_h_setup
    const_h += '#define VLANY_PASSWORD "' + xor(crypt.crypt(VLANY_PASSWORD, "$6%0s" % (''.join(random.choice(string.ascii_lowercase + string.ascii_uppercase + string.digits) for x in range(12))))) + '"\n'
  File "config.py", line 169, in xor
    return ''.join(list('\\x'+hex(ord(x) ^ 0xac)[2:] for x in str_))
TypeError: 'NoneType' object is not iterable
Configuration failed. Exiting.

Please help me and thanks for your attention
Sorry for bad english

**Comment by unixfox** [comment]
It's my fault like I said here: https://github.com/mempodippy/vlany/issues/13#issuecomment-273484532
I'll revert the pull request that cause this problem.
