### ISSUE TITLE
Installation fails on Debian 7/Ubuntu 14.04 because LibSSL package isn't multiarch.

### ISSUE THREAD

**Issue by unixfox** [mempodippy/vlany#17]
I'm facing to an issue because Debian 7 Wheezy doesn't want to keep the package `libssl-dev` (64 bits) and `libssl-dev:i386` (32 bits) at the same time because [libssl is not multiarch compatible](http://askubuntu.com/questions/252168/can-i-install-libssl-devi386-on-x86-64-system-without-losing-important-packag).
```
root@vlany:~# apt-get --yes --force-yes install libssl-dev:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libssl-doc zlib1g-dev
Use 'apt-get autoremove' to remove them.
Recommended packages:
  libssl-doc:i386
The following packages will be REMOVED:
  libssl-dev
The following NEW packages will be installed:
  libssl-dev:i386
0 upgraded, 1 newly installed, 1 to remove and 27 not upgraded.
Need to get 0 B/1,626 kB of archives.
After this operation, 1,411 kB disk space will be freed.
(Reading database ... 37977 files and directories currently installed.)
Removing libssl-dev ...
Selecting previously unselected package libssl-dev.
(Reading database ... 37892 files and directories currently installed.)
Unpacking libssl-dev (from .../libssl-dev_1.0.1t-1+deb7u2_i386.deb) ...
Setting up libssl-dev (1.0.1t-1+deb7u2) ...
```
So I ask you @mempodippy if it's needed to have the 32 bits libraries on a 64 bits system for vlany?

**Comment by mempodippy** [comment]
Yes. If not, 32 bit library symbols can be used to circumvent the kit. Just makes sure that everything that needs hooked is actually hooked.

**Comment by unixfox** [comment]
So it's better to have the `libssl-dev` or `libssl-dev:i386`? Because Debian 7 and older versions of Ubuntu doesn't support multiarch for libssl.

**Comment by unixfox** [comment]
I'll make a temporally patch to skip build for 32 bits support because Debian 7 fails to install vlany, are you ok ?

**Comment by mempodippy** [comment]
I'm alright, just stuff... Development will become more regular after this weekend for a length of time.
