### ISSUE TITLE
Segmentation fault when running the su command

### ISSUE THREAD

**Issue by corefx** [mempodippy/vlany#20]
I noticed that the su command segfaults when Vlany is installed (tested on Debian 8) but the **su -** command works fine. 
![su](https://cloud.githubusercontent.com/assets/10615238/24324988/044864de-1199-11e7-8a74-14c27bc974c1.png)

**Comment by mempodippy** [comment]
Should be fixed. I was trying to check the first additional argument after su, when it might not even exist. Thanks. :smile:
