### ISSUE TITLE
Failed to start udev Kernel Device Manager on Ubuntu 16.04

### ISSUE THREAD

**Issue by BryceeeeeChen** [mempodippy/vlany#31]
Hi,
Thank you for sharing this awesome rootkit project. 
I tried some hiding features right after the installation on Ubuntu 16.04.4 server (4.4.0-116-generic) and they worked perfectly. However, when I rebooted the machine, the OS failed to boot into the default mode.
Could you help me to solve this problem? Thanks!
![img_6784](https://user-images.githubusercontent.com/16990429/42088968-0830f9b2-7bce-11e8-8d25-b5a76eacf499.JPG)

**Comment by unixfox** [comment]
It's written on the readme: https://github.com/mempodippy/vlany#serious-bugs
> There is currently an experimental reboot brick fix. Some systems will brick, others won't. Please report any systems that brick on reboot as an issue, and give the circumstances of the vlany installation in the report. Take a look at the Issues page to see if a similar issue has already been submitted.
Any Linux distro with systemd will fail on the reboot, there is an issue here about that: https://github.com/mempodippy/vlany/issues/21
