### ISSUE TITLE
Logged in users are shown twice

### ISSUE THREAD

**Issue by corefx** [mempodippy/vlany#4]
Hi,

I have noticed this bug when testing vlany on debian 8, ubuntu 14.04 and 16.04 (using virtualbox) 
See following screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/10615238/20005082/b9976de6-a298-11e6-8432-50f36fba0c3a.png)

**Comment by mempodippy** [comment]
I've honestly never came across this bug during development.

![capture](https://cloud.githubusercontent.com/assets/19416758/20007301/7deda936-a293-11e6-8f17-1103d40f7e02.PNG)

I don't understand what's causing this, but I'll have a little poke around. 😄
